SDK and workflow for error codes
redhat-developer/app-services-sdk-js pull request #252
Opened 2022-01-14 17:02 UTC by wtrocki

## How this works

1. Error codes are generated as 3th job due to additional timing needed for QA to pickup error updates.
2. Error codes are generated only on API change due to fact that we agreed with teams to change openapi when errors are changed. This is simpler rather than constraining team to have all errors in the single file.
3. Once Job is triggered we fetch all APIs 

## Notes

COS api is not on stage yet but I have added it manually to provide early support.
Solution provided is dedicated to this SDK. Other SDKS will use different patterns.

## Verification

Will work with @riccardo-forina to replace existing error codes and use SDK once merged.

2022-01-14 17:03 UTC, wtrocki commented on packages/kafka-management-sdk/src/errors.ts
> +
This is the most relevant part of the PR

2022-01-14 17:09 UTC, wtrocki commented
I need to add error handling to examples

2022-01-17 08:26 UTC, riccardo-forina approved these changes
LGTM

2022-01-17 09:41 UTC, wtrocki commented
Will wait for @craicoverflow review and integrate that with kas-ui

2022-01-17 10:24 UTC, craicoverflow requested changes
Some errors with the path to scripts that I found when manually running them based off what is described in the GitHub job.

You can also see this won't work when using act:

```shell
act -j generateErrors
...
[Generate Errors SDK/generateErrors] ⭐  Run Fetch Errors JSON files
[Generate Errors SDK/generateErrors]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /Users/ephelan/code/src/github.com/redhat-developer/app-services-sdk-js/workflow/2] user= workdir=
| /Users/ephelan/code/src/github.com/redhat-developer/app-services-sdk-js/workflow/2: line 1: ./scripts/fetch-errors.sh: No such file or directory
[Generate Errors SDK/generateErrors]   ❌  Failure - Fetch Errors JSON files
Error: exit with `FAILURE`: 127
```

2022-01-17 10:24 UTC, craicoverflow commented on .github/workflows/generate_errors.yaml
> +        run: ./scripts/fetch-errors.sh
Incorrect path:

```suggestion
        run: ./scripts/errors/fetch-errors.sh
```

2022-01-17 10:24 UTC, craicoverflow commented on .github/workflows/generate_errors.yaml
> +        run: ./scripts/generate-errors.sh
Incorrect path:

```suggestion
        run: ./scripts/errors/generate-errors.sh
```

2022-01-17 10:24 UTC, craicoverflow commented on scripts/errors/generate-errors.sh
> +node ./generate-errors.js
When I run generate-errors.sh from the root of the project I get an error. You might want to add the path prefix with `pwd`.

```shell
$ ./scripts/errors/generate-errors.sh
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/ephelan/code/src/github.com/redhat-developer/app-services-sdk-js/generate-errors.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

2022-01-17 10:24 UTC, craicoverflow commented on packages/registry-management-sdk/src/errors.ts
> +  ERROR_1 = "SRS-MGMT-1",
The enum key should be indented IMO.

2022-01-17 13:14 UTC, wtrocki commented on packages/connector-management-sdk/src/errors.ts
> +  ERROR_4 = "KAFKAS-MGMT-4",
It is possible but would require extra field on the backend. I have that planned for phase 2 of the SDKs

2022-01-17 13:28 UTC, craicoverflow approved these changes

2022-01-17 13:38 UTC, wtrocki commented
Merging so I can do proper release. Already tested it with UI

2022-01-17 13:38 UTC, merged