feat: implement sorting of topics through keys
redhat-developer/app-services-sdk-js pull request #72
Opened 2021-06-23 13:11 UTC by rkpattnaik780

* Fix some error arising due to wrong path in mock server.
* Support filtering of topics by key.

2021-06-23 13:37 UTC, craicoverflow requested changes
Works great! Needs one change regarding the path to the OpenAPI files though.

2021-06-23 13:37 UTC, craicoverflow commented on packages/api-mock/src/index.js
>  });
These are pointing to the OpenAPI files located in `app-services-sdk-js/packages/api-mock/openapi`. Is the problem that these are out of date with the ones at in `.openapi`?

If so, it will be better to make copies of them, as the mock OpenAPIs can vary from the production ones, for example we may want to create mock handlers before they exist in the API.

2021-06-24 07:38 UTC, rkpattnaik780 commented on packages/api-mock/src/index.js
>  });
sdk was throwing error file not found in dev mode (npm start). And I can see there's no directory `app-services-sdk-js/packages/api-mock/openapi`. The only yaml files I can get with `Ctrl + P` are the ones within `.openapi` directory.

2021-06-24 07:40 UTC, rkpattnaik780 commented on packages/api-mock/src/index.js
>  });
![Screenshot from 2021-06-24 13-06-50](https://user-images.githubusercontent.com/23582438/123222367-81813b80-d4ed-11eb-8b2c-6630654c3d4d.png)

2021-06-24 07:59 UTC, craicoverflow commented on packages/api-mock/src/index.js
>  });
You need to run `yarn build` first - this copies those files into that directory: https://github.com/redhat-developer/app-services-sdk-js/tree/main/packages/api-mock#local-development

2021-06-24 08:00 UTC, wtrocki commented on packages/api-mock/src/index.js
>  });
yes. npm publish cannot take resources outside current folder so files need to be copied and transformed. Readme.md has info but might be not well explained.

2021-06-24 10:37 UTC, wtrocki commented on packages/api-mock/src/index.js
>  });
My recomendation would be to revert this changes if possible. Then we can merge - all works.

2021-06-24 12:00 UTC, wtrocki approved these changes

2021-06-24 12:01 UTC, wtrocki commented
Love how mature mock is. Note that we are still missing some new fields in mock like `page` that were added to API recently.
Issue here #65

2021-06-24 12:01 UTC, merged